In [7]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

class NeuralNetwork:
    def __init__(self, input_size, hidden_size, output_size):
        self.input_size = input_size
        self.hidden_size = hidden_size
        self.output_size = output_size
        
        # Initialize weights randomly
        self.weights_input_hidden = np.random.randn(self.input_size, self.hidden_size)
        self.weights_hidden_output = np.random.randn(self.hidden_size, self.output_size)
        
    def feedforward(self, X):
        self.hidden_input = np.dot(X, self.weights_input_hidden)
        self.hidden_output = sigmoid(self.hidden_input)
        self.final_input = np.dot(self.hidden_output, self.weights_hidden_output)
        self.final_output = sigmoid(self.final_input)
        return self.final_output
    
    def backward(self, X, y, output):
        self.error = y - output
        self.d_output = self.error * sigmoid_derivative(output)
        self.error_hidden = np.dot(self.d_output, self.weights_hidden_output.T)
        self.d_hidden = self.error_hidden * sigmoid_derivative(self.hidden_output)
        
        # Update weights
        self.weights_hidden_output += np.dot(self.hidden_output.T, self.d_output)
        self.weights_input_hidden += np.dot(X.T, self.d_hidden)
        
    def train(self, X, y, epochs):
        for _ in range(epochs):
            output = self.feedforward(X)
            self.backward(X, y, output)

# Sample dataset (XOR problem)
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [1], [1], [0]])

# Create and train the neural network
input_size = 2
hidden_size = 3  # Increase nodes in the hidden layer
output_size = 1
epochs = 10000

nn = NeuralNetwork(input_size, hidden_size, output_size)
nn.train(X, y, epochs)

# Test the trained model
X_test = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
predicted_output = nn.feedforward(X_test)
print("For Hidden Layers = 3 and sigmoid Function")
print("Predicted Output:")
print(predicted_output)


# Create and train the neural network
input_size = 2
hidden_size = 4  # Increase nodes in the hidden layer
output_size = 1
epochs = 10000

nn = NeuralNetwork(input_size, hidden_size, output_size)
nn.train(X, y, epochs)

# Test the trained model
X_test = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
predicted_output = nn.feedforward(X_test)
print("For Hidden Layers = 4 and sigmoid Function")
print("Predicted Output:")
print(predicted_output)


# Create and train the neural network
input_size = 2
hidden_size = 2  # Increase nodes in the hidden layer
output_size = 1
epochs = 10000

nn = NeuralNetwork(input_size, hidden_size, output_size)
nn.train(X, y, epochs)

# Test the trained model
X_test = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
predicted_output = nn.feedforward(X_test)
print("For Hidden Layers = 2 and sigmoid Function")
print("Predicted Output:")
print(predicted_output)

For Hidden Layers = 3 and sigmoid Function
Predicted Output:
[[0.07532897]
 [0.94404447]
 [0.9469794 ]
 [0.05129775]]
For Hidden Layers = 4 and sigmoid Function
Predicted Output:
[[0.01795995]
 [0.98348678]
 [0.98801677]
 [0.014566  ]]
For Hidden Layers = 2 and sigmoid Function
Predicted Output:
[[0.03189968]
 [0.93224081]
 [0.93224077]
 [0.09037125]]


In [14]:
import numpy as np

# tanh activation function
def tanh(x):
    return (np.exp(x) - np.exp(-x)) / (np.exp(x) + np.exp(-x))

def tanh_derievative(x):
    numerator = np.exp(x) - np.exp(-x)
    denominator = np.exp(x) + np.exp(-x)
    return 1 - (numerator / denominator)**2

class NeuralNetwork:
    def __init__(self, input_size, hidden_size, output_size):
        self.input_size = input_size
        self.hidden_size = hidden_size
        self.output_size = output_size
        
        # Initialize weights randomly
        self.weights_input_hidden = np.random.randn(self.input_size, self.hidden_size)
        self.weights_hidden_output = np.random.randn(self.hidden_size, self.output_size)
        
    def feedforward(self, X):
        self.hidden_input = np.dot(X, self.weights_input_hidden)
        self.hidden_output = tanh(self.hidden_input)
        self.final_input = np.dot(self.hidden_output, self.weights_hidden_output)
        self.final_output = tanh(self.final_input)
        return self.final_output
    
    def backward(self, X, y, output):
        self.error = y - output
        self.d_output = self.error * (1 - (tanh(output) ** 2))
        self.error_hidden = np.dot(self.d_output, self.weights_hidden_output.T)
        self.d_hidden = self.error_hidden * (1 - (tanh(self.hidden_output) ** 2))
        
        # Update weights
        self.weights_hidden_output += np.dot(self.hidden_output.T, self.d_output)
        self.weights_input_hidden += np.dot(X.T, self.d_hidden)
        
    def train(self, X, y, epochs):
        for _ in range(epochs):
            output = self.feedforward(X)
            self.backward(X, y, output)

# Sample dataset (XOR problem)
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [1], [1], [0]])

# Create and train the neural network
input_size = 2
hidden_size = 3  # Increase nodes in the hidden layer
output_size = 1
epochs = 10000

nn = NeuralNetwork(input_size, hidden_size, output_size)
nn.train(X, y, epochs)

# Test the trained model
X_test = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
predicted_output = nn.feedforward(X_test)
print("For Hidden Layers = 3 and Tanh Function")
print("Predicted Output:")
print(predicted_output)


# Create and train the neural network
input_size = 2
hidden_size = 4  # Increase nodes in the hidden layer
output_size = 1
epochs = 10000

nn = NeuralNetwork(input_size, hidden_size, output_size)
nn.train(X, y, epochs)

# Test the trained model
X_test = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
predicted_output = nn.feedforward(X_test)
print("For Hidden Layers = 4 and Tanh Function")
print("Predicted Output:")
print(predicted_output)


# Create and train the neural network
input_size = 2
hidden_size = 2  # Increase nodes in the hidden layer
output_size = 1
epochs = 10000

nn = NeuralNetwork(input_size, hidden_size, output_size)
nn.train(X, y, epochs)

# Test the trained model
X_test = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
predicted_output = nn.feedforward(X_test)
print("For Hidden Layers = 2 and Tanh Function")
print("Predicted Output:")
print(predicted_output)

For Hidden Layers = 3 and Tanh Function
Predicted Output:
[[0.        ]
 [0.9682928 ]
 [0.9682928 ]
 [0.79242634]]
For Hidden Layers = 4 and Tanh Function
Predicted Output:
[[0.        ]
 [0.96498267]
 [0.96498267]
 [0.74971464]]
For Hidden Layers = 2 and Tanh Function
Predicted Output:
[[0.        ]
 [0.73203041]
 [0.3317664 ]
 [0.73403108]]


In [15]:
import numpy as np
import tensorflow as tf

# Define the XOR dataset
inputs = np.array([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=np.float32)
outputs = np.array([[0], [1], [1], [0]], dtype=np.float32)

# Define the model architecture
model = tf.keras.Sequential([
    tf.keras.layers.Dense(2, activation='relu', input_shape=(2,)),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(inputs, outputs, epochs=1000, verbose=0)

# Evaluate the model
loss, accuracy = model.evaluate(inputs, outputs, verbose=0)
print(f'Accuracy: {accuracy}')

# Predict using the trained model
predictions = model.predict(inputs)
print(f'Predictions:\n{predictions}')


Accuracy: 0.5
1/1 [==============================] - 0s 44ms/step
Predictions:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
