In [11]:
import numpy as np

# Define the XOR data
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
Y = np.array([[0], [1], [1], [0]])

# Define the architecture of the MLP
input_size = 2
hidden_size = 2
output_size = 1

# Initialize weights and biases for the hidden and output layers
hidden_weights = np.array([[0.1, 0.2], [-0.3, -0.4]])
hidden_bias = np.array([[0.5, 0.6]])
output_weights = np.array([[0.7], [-0.8]])
output_bias = np.array([[-0.9]])

# Define the sigmoid activation function and its derivative
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Function to print the initial weights and biases
def print_initial_weights_and_biases():
    print("Initial Hidden Layer Weights:")
    print(hidden_weights)
    print("Initial Hidden Layer Bias:")
    print(hidden_bias)
    print("Initial Output Layer Weights:")
    print(output_weights)
    print("Initial Output Layer Bias:")
    print(output_bias)

# Print the initial weights and biases
print_initial_weights_and_biases()

# Training parameters
learning_rate = 0.1
epochs = 10000

# Training loop
for epoch in range(epochs):
    # Forward pass
    hidden_input = np.dot(X, hidden_weights) + hidden_bias
    hidden_output = sigmoid(hidden_input)
    output_input = np.dot(hidden_output, output_weights) + output_bias
    output_output = sigmoid(output_input)
    
    # Calculate the error
    error = Y - output_output
    
    # Backpropagation
    d_output = error * output_output * (1 - output_output)
    error_hidden = d_output.dot(output_weights.T)
    d_hidden = error_hidden * hidden_output * (1 - hidden_output)
    
    # Update weights and biases
    output_weights += hidden_output.T.dot(d_output) * learning_rate
    output_bias += np.sum(d_output, axis=0, keepdims=True) * learning_rate
    hidden_weights += X.T.dot(d_hidden) * learning_rate
    hidden_bias += np.sum(d_hidden, axis=0, keepdims=True) * learning_rate

# Print the updated weights and biases after training
print("Updated Hidden Layer Weights:")
print(hidden_weights)
print("Updated Hidden Layer Bias:")
print(hidden_bias)
print("Updated Output Layer Weights:")
print(output_weights)
print("Updated Output Layer Bias:")
print(output_bias)

# Make predictions
predictions = sigmoid(np.dot(sigmoid(np.dot(X, hidden_weights) + hidden_bias), output_weights) + output_bias)

# Print predictions
for i in range(len(X)):
    print(f"Input: {X[i]}, Predicted: {predictions[i][0]:.4f},  Actual: {Y[i][0]}")


Initial Hidden Layer Weights:
[[ 0.1  0.2]
 [-0.3 -0.4]]
Initial Hidden Layer Bias:
[[0.5 0.6]]
Initial Output Layer Weights:
[[ 0.7]
 [-0.8]]
Initial Output Layer Bias:
[[-0.9]]
Updated Hidden Layer Weights:
[[ 4.43789806  5.52327682]
 [-4.68717045 -5.51577963]]
Updated Hidden Layer Bias:
[[-2.42140995  2.88443117]]
Updated Output Layer Weights:
[[ 7.47382455]
 [-6.90745184]]
Updated Output Layer Bias:
[[3.14212427]]
Input: [0 0], Predicted: 0.0579,  Actual: 0
Input: [0 1], Predicted: 0.9361,  Actual: 1
Input: [1 0], Predicted: 0.9444,  Actual: 1
Input: [1 1], Predicted: 0.0512,  Actual: 0
